# Generated by Django 4.0.2 on 2022-02-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_rename_date_created_orders_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='order',
        ),
    ]
