# Generated by Django 4.0.2 on 2022-02-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
