# Generated by Django 4.0.2 on 2022-02-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_list',
            field=models.FileField(default=' ', upload_to='myfiles/'),
        ),
    ]
