# Generated by Django 4.0.2 on 2022-02-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_remove_product_name_product_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
